-- brand_images.vision_tags — nullable JSONB payload populated by the
-- image-vision-tagger background job. Nullable and no default so existing
-- rows read as NULL until the tagger backfills them. Expected shape:
--   {
--     has_people: boolean,
--     scene_type: 'lifestyle' | 'product' | 'texture' | 'logo' | 'other',
--     mood: string[],
--     composition_quality: 1 | 2 | 3 | 4 | 5,
--     suitable_for: string[],   -- ad-copy angles
--     description: string,
--     tagged_at: string         -- ISO timestamp
--   }
--
-- No CHECK constraint on the JSON shape — validation lives in the application
-- layer (src/lib/image-vision-tagger.ts). Keeping the column schemaless lets
-- us iterate on the fields without a DB migration each time.
alter table brand_images add column vision_tags jsonb;
